table campaign_skus
	lineageTag: 7a3aa4b2-cd98-4283-98e4-5370fdca5ada

	column Column1
		dataType: string
		lineageTag: 281ab257-39c0-46c9-a2aa-e64ce58d2d8c
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 9f1d5a07-7471-4f36-aec7-de5a3dc4e333
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition campaign_skus = m
		mode: import
		queryGroup: 01_Stage
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\dev\dimensional-data-modeling-portfolio\local-data\dataset.xlsx"), null, true),
				    campaign_skus_Sheet = Quelle{[Item="campaign_skus",Kind="Sheet"]}[Data],
				    #"Geänderter Typ" = Table.TransformColumnTypes(campaign_skus_Sheet,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

