table channels
	lineageTag: 24db463b-804b-47f4-846d-b4a696684df3

	column channel_code
		dataType: int64
		formatString: 0
		lineageTag: 297f31de-3daa-4d63-b97a-d26cd7434387
		summarizeBy: none
		sourceColumn: channel_code

		annotation SummarizationSetBy = Automatic

	column channel_name
		dataType: string
		lineageTag: ebc095ca-c8ff-4336-b88d-8ca491097655
		summarizeBy: none
		sourceColumn: channel_name

		annotation SummarizationSetBy = Automatic

	partition channels = m
		mode: import
		queryGroup: 01_Stage
		source =
				let
				    Quelle = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjRQ0lHyz8vJzEtVCC7JL0pVitWJVjICiQalliRm5igEJBaV5KUWgcWNQeLhGfk5qcWJORClJiAht8zUnBSFYLBYLAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [channel_code = _t, channel_name = _t]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(Quelle,{{"channel_code", Int64.Type}, {"channel_name", type text}})
				in
				    #"Geänderter Typ"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

