table cities
	lineageTag: 97ff0a4b-1d0d-46cd-8740-a21dc35075cd

	column Column1
		dataType: string
		lineageTag: 693d4063-2b13-4677-b275-19e45e79ab87
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 4bd09e3e-fc03-4700-afc5-9595761cea8e
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition cities = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\Users\admin\Desktop\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				    cities_Sheet = Quelle{[Item="cities",Kind="Sheet"]}[Data],
				    #"Geänderter Typ" = Table.TransformColumnTypes(cities_Sheet,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

