table CUST_MASTER
	lineageTag: 6b15468f-b3c6-423a-953f-7cf80687403d

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 53958678-2c7c-47b2-99ea-420086c4b52e
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 66bc9e93-4186-4da3-8928-1bb8d9b980ed
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 9081c190-f3ee-4ee8-aedc-e8d34a7467b3
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column AddressID
		dataType: int64
		formatString: 0
		lineageTag: 62aa2d79-4cde-4dc4-ae0e-88f1d91f43a2
		summarizeBy: none
		sourceColumn: AddressID

		annotation SummarizationSetBy = Automatic

	column AccountManager
		dataType: string
		lineageTag: ebc0d2ff-4bfb-4915-9da8-76b1c53da055
		summarizeBy: none
		sourceColumn: AccountManager

		annotation SummarizationSetBy = Automatic

	column PaymentTerms
		dataType: string
		lineageTag: bda00c00-bd8f-485a-afc8-6ac90faf6eb0
		summarizeBy: none
		sourceColumn: PaymentTerms

		annotation SummarizationSetBy = Automatic

	column hash_key
		dataType: string
		lineageTag: 17320a71-110e-45d6-9fc3-d7206a5d1c17
		summarizeBy: none
		sourceColumn: hash_key

		annotation SummarizationSetBy = Automatic

	column source_id
		dataType: string
		lineageTag: d0488058-e49e-431e-9487-02a07920cf32
		summarizeBy: none
		sourceColumn: source_id

		annotation SummarizationSetBy = Automatic

	partition CUST_MASTER = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\dev\dimensional-data-modeling-portfolio\local-data\dataset.xlsx"), null, true),
				    CUST_MASTER_Sheet = Quelle{[Item="CUST_MASTER",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(CUST_MASTER_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"CustomerID", Int64.Type}, {"CustomerName", type text}, {"Segment", type text}, {"AddressID", Int64.Type}, {"AccountManager", type text}, {"PaymentTerms", type text}, {"hash_key", type text}, {"source_id", type text}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

