table customer_contacts
	lineageTag: 94535f5c-5608-4c9e-b576-43f0964cd9e1

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: ecc56984-1eb2-471f-9ec0-ea5116e41ddc
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ContactName
		dataType: string
		lineageTag: b3b9c684-1a75-4fdd-b22d-6bd45d38c402
		summarizeBy: none
		sourceColumn: ContactName

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: bd7a56bc-d970-4699-ae7c-8d0963bb4270
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column IsPrimary
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3861156e-a986-4292-b97f-2c7859023b11
		summarizeBy: none
		sourceColumn: IsPrimary

		annotation SummarizationSetBy = Automatic

	partition customer_contacts = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\dev\dimensional-data-modeling-portfolio\local-data\dataset.xlsx"), null, true),
				    customer_contacts_Sheet = Quelle{[Item="customer_contacts",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(customer_contacts_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"CustomerID", Int64.Type}, {"ContactName", type text}, {"Email", type text}, {"IsPrimary", type logical}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

