table exchange_rates
	lineageTag: 38bf1470-7133-4b9a-b1c4-dd026eaf1462

	column Currency
		dataType: string
		lineageTag: 8cd19022-9e6d-4a5a-bff2-d1a940c44665
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column Rate
		dataType: double
		lineageTag: cc918285-29f7-4543-adc6-7f06a71dca76
		summarizeBy: sum
		sourceColumn: Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 993b2b92-ae97-4023-95ed-2daa6606f91f
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 2ff82b0a-6183-44c6-8e3a-c2a163158afd
			defaultHierarchy: LocalDateTable_e91117fa-526d-4546-94d7-cde389d13941.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition exchange_rates = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\Users\admin\Desktop\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				    exchange_rates_Sheet = Quelle{[Item="exchange_rates",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(exchange_rates_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Currency", type text}, {"Rate", type number}, {"Date", type date}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

