table fact_promotion_coverage
	lineageTag: 22b056bc-64d3-47e3-a025-64549eebd992

	column campaign_key
		dataType: int64
		formatString: 0
		lineageTag: b35f9c60-491b-4b9d-8ac0-2426aa2cb913
		summarizeBy: none
		sourceColumn: campaign_key

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		formatString: 0
		lineageTag: e8bef332-e1ea-445f-b269-5f57b7133399
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	partition fact_promotion_coverage = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Quelle = campaign_skus,
				    #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"CampaignName", type text}, {"PromotedSKUs", type text}}),
				    #"Spalte nach Trennzeichen teilen" = Table.ExpandListColumn(Table.TransformColumns(#"Geänderter Typ", {{"PromotedSKUs", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "PromotedSKUs"),
				    #"Geänderter Typ1" = Table.TransformColumnTypes(#"Spalte nach Trennzeichen teilen",{{"PromotedSKUs", type text}}),
				    #"Abgeschnittener Text" = Table.TransformColumns(#"Geänderter Typ1",{{"PromotedSKUs", Text.Trim, type text}}),
				    #"Zusammengeführte Abfragen" = Table.NestedJoin(#"Abgeschnittener Text", {"CampaignName"}, dim_campaign, {"campaign_name"}, "dim_campaign", JoinKind.LeftOuter),
				    #"Erweiterte dim_campaign" = Table.ExpandTableColumn(#"Zusammengeführte Abfragen", "dim_campaign", {"campaign_key"}, {"dim_campaign.campaign_key"}),
				    #"Zusammengeführte Abfragen1" = Table.NestedJoin(#"Erweiterte dim_campaign", {"PromotedSKUs"}, dim_product, {"product_code"}, "dim_product", JoinKind.LeftOuter),
				    #"Erweiterte dim_product" = Table.ExpandTableColumn(#"Zusammengeführte Abfragen1", "dim_product", {"product_key"}, {"dim_product.product_key"}),
				    #"Umbenannte Spalten" = Table.RenameColumns(#"Erweiterte dim_product",{{"dim_product.product_key", "product_key"}, {"dim_campaign.campaign_key", "campaign_key"}}),
				    #"Entfernte Spalten" = Table.RemoveColumns(#"Umbenannte Spalten",{"CampaignName", "PromotedSKUs"})
				in
				    #"Entfernte Spalten"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

