table fact_sales_targets
	lineageTag: 4ae16382-f196-43ee-9f63-2dd8c270bbe9

	column period
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: e651ff19-5432-432e-ab73-71c50794a0d8
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column target_revenue
		dataType: int64
		formatString: 0
		lineageTag: 308240ca-3419-41d0-a6c7-903f16b2cc71
		summarizeBy: sum
		sourceColumn: target_revenue

		annotation SummarizationSetBy = Automatic

	partition fact_sales_targets = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    Quelle = sales_targets,
				    #"Umbenannte Spalten" = Table.RenameColumns(Quelle,{{"Period", "period"}, {"TargetRevenue", "target_revenue"}})
				in
				    #"Umbenannte Spalten"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

