table fact_order_process
	lineageTag: b8a3788c-9201-4c70-8ab9-30c6e9b6e5d8

	column order_id
		dataType: string
		lineageTag: a62f3aa0-d4d6-4054-9bef-664e740a0311
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: e2ffa820-f569-4d0b-b3b1-8718b15c0fea
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 11746200-4529-415b-b3f6-7d99840a70d8
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column ship_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 5e8129b6-ec77-474c-95dc-03668acc8c93
		summarizeBy: none
		sourceColumn: ship_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column delivery_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 24acedd9-fb19-4080-8cd4-55fcf3b6178e
		summarizeBy: none
		sourceColumn: delivery_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column invoice_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: ffd9435b-dee6-4913-89ff-93ca002ec3c3
		summarizeBy: none
		sourceColumn: invoice_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column pay_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 70a98b65-b162-4b42-82c4-731845e1dee2
		summarizeBy: none
		sourceColumn: pay_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column order_to_pay = DATEDIFF(fact_order_process[order_date], fact_order_process[pay_date], DAY)
		formatString: 0
		lineageTag: b08a06de-8725-4db7-a439-26b32a7d5bb7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fact_order_process = m
		mode: import
		queryGroup: 03_Facts
		source =
				let
				    SourceOrders = orders,
				    OrderSpine = Table.RemoveColumns(SourceOrders,{"CustomerCity", "RegionName", "ShipToCity", "BillToCity", "OrderChannel", "Status", "Priority", "OrderTotal"}),
				    CustomerLookup = Table.NestedJoin(OrderSpine, {"CustomerName"}, dim_customer, {"customer_name"}, "dim_customer", JoinKind.LeftOuter),
				    CustomerExpanded = Table.ExpandTableColumn(CustomerLookup, "dim_customer", {"customer_id"}, {"customer_id"}),
				    CustomerClean = Table.RemoveColumns(CustomerExpanded,{"CustomerName"}),
				    ShipmentMilestones = Table.Group(shipments, {"OrderID"}, {
				        {"ship_date", each try List.Min(List.RemoveNulls([ShipDate])) otherwise null, type nullable date},
				        {"delivery_date", each try List.Max(List.RemoveNulls([DeliveryDate])) otherwise null, type nullable date}
				    }),
				    PaymentMilestones = Table.Group(payments, {"InvoiceID"}, {
				        {"pay_date", each try List.Max(List.RemoveNulls([PayDate])) otherwise null, type nullable date}
				    }),
				    InvoicePaymentBase = Table.NestedJoin(INVOICES, {"InvoiceID"}, PaymentMilestones, {"InvoiceID"}, "payment", JoinKind.LeftOuter),
				    InvoicePaymentExpanded = Table.ExpandTableColumn(InvoicePaymentBase, "payment", {"pay_date"}, {"pay_date"}),
				    InvoiceMilestones = Table.Group(InvoicePaymentExpanded, {"OrderID"}, {
				        {"invoice_date", each try List.Min(List.RemoveNulls([InvoiceDate])) otherwise null, type nullable date},
				        {"pay_date", each try List.Max(List.RemoveNulls([pay_date])) otherwise null, type nullable date}
				    }),
				    ShipmentJoin = Table.NestedJoin(CustomerClean, {"OrderID"}, ShipmentMilestones, {"OrderID"}, "shipment", JoinKind.LeftOuter),
				    ShipmentExpanded = Table.ExpandTableColumn(ShipmentJoin, "shipment", {"ship_date", "delivery_date"}, {"ship_date", "delivery_date"}),
				    InvoiceJoin = Table.NestedJoin(ShipmentExpanded, {"OrderID"}, InvoiceMilestones, {"OrderID"}, "invoice", JoinKind.LeftOuter),
				    InvoiceExpanded = Table.ExpandTableColumn(InvoiceJoin, "invoice", {"invoice_date", "pay_date"}, {"invoice_date", "pay_date"}),
				    Renamed = Table.RenameColumns(InvoiceExpanded,{{"OrderID", "order_id"}, {"OrderDate", "order_date"}}),
				    Reordered = Table.ReorderColumns(Renamed,{"order_id", "customer_id", "order_date", "ship_date", "delivery_date", "invoice_date", "pay_date"}),
				    NormalizedOrderDate = Table.TransformColumnTypes(Reordered,{{"order_date", type date}})
				in
				    NormalizedOrderDate

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

