table INVOICES
	lineageTag: 5df1024b-1107-4072-8f57-abc0e452c3b0

	column InvoiceID
		dataType: string
		lineageTag: bfaee95b-971f-4ad9-9868-ac872e9f8ce8
		summarizeBy: none
		sourceColumn: InvoiceID

		annotation SummarizationSetBy = Automatic

	column OrderID
		dataType: string
		lineageTag: e04ffe75-679d-48c0-bd84-014d6da73d17
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: c783d01e-a69d-46d2-865c-8ef5a5bf6207
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column InvoiceDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 660fb5b6-5357-4adc-8581-dcd2f399ad5a
		summarizeBy: none
		sourceColumn: InvoiceDate

		variation Variation
			isDefault
			relationship: f5850f65-83e8-49f9-9b83-650ee3ae1827
			defaultHierarchy: LocalDateTable_73ccc87d-f682-4819-9c48-bd109fd0653f.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Amount
		dataType: double
		lineageTag: 2ec1f9f9-a85e-4dc0-8d02-204c07ff301c
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition INVOICES = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\Users\admin\Desktop\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				    INVOICES_Sheet = Quelle{[Item="INVOICES",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(INVOICES_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"InvoiceID", type text}, {"OrderID", type text}, {"CustomerName", type text}, {"InvoiceDate", type date}, {"Amount", type number}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

