table invoice_lines
	lineageTag: 65064b52-c1f6-42d9-9207-a0e1ad8aebcb

	column InvoiceLineID
		dataType: string
		lineageTag: 83fb5c0d-3f64-439c-8580-c5e2a54cc3fd
		summarizeBy: none
		sourceColumn: InvoiceLineID

		annotation SummarizationSetBy = Automatic

	column InvoiceID
		dataType: string
		lineageTag: e4f7adc2-32f0-4ae4-8d29-9a57da3bb965
		summarizeBy: none
		sourceColumn: InvoiceID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: f29787b1-5b78-4569-9951-68da73ec1892
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		lineageTag: 0139bb7f-d425-4bd9-8223-8a1057e7dc39
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition invoice_lines = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\Users\admin\Desktop\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				    invoice_lines_Sheet = Quelle{[Item="invoice_lines",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(invoice_lines_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"InvoiceLineID", type text}, {"InvoiceID", type text}, {"ProductName", type text}, {"Amount", type number}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

