table orders
	lineageTag: 11f8a8cb-b77f-4f93-b512-5656e0f3bea0

	column OrderID
		dataType: string
		lineageTag: f331180b-af4f-4434-aea3-dc43182343fb
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 53590753-de34-4d40-bac0-1bbfd9110a88
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column CustomerCity
		dataType: string
		lineageTag: 497caa83-deae-4dae-8cb0-fbb455ed96a2
		summarizeBy: none
		sourceColumn: CustomerCity

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		lineageTag: 289380ee-a332-4fdd-9161-9d95000d086c
		summarizeBy: none
		sourceColumn: RegionName

		annotation SummarizationSetBy = Automatic

	column ShipToCity
		dataType: string
		lineageTag: b8b55d21-e9c3-4e8f-a9a4-8e091078013a
		summarizeBy: none
		sourceColumn: ShipToCity

		annotation SummarizationSetBy = Automatic

	column BillToCity
		dataType: string
		lineageTag: 6307ad72-c130-49a7-8fc9-1848e0c03608
		summarizeBy: none
		sourceColumn: BillToCity

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 308ce68a-c40a-44c8-a018-8ff347eba6c3
		summarizeBy: none
		sourceColumn: OrderDate

		variation Variation
			isDefault
			relationship: 1995bda7-ff5b-4741-b340-7fe2c272c359
			defaultHierarchy: LocalDateTable_369d10e7-9642-4f7d-93e9-a01d648be43f.Datumshierarchie

		annotation SummarizationSetBy = Automatic

	column OrderChannel
		dataType: int64
		formatString: 0
		lineageTag: 0105860d-8545-42f3-a758-60c3bee0f8d3
		summarizeBy: sum
		sourceColumn: OrderChannel

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 8413a55d-739a-4ca9-93d4-7c8362d92f0d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 8be9a89e-2363-457f-a862-c80616c77b4e
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column OrderTotal
		dataType: double
		lineageTag: 293aa3bb-630e-486a-a835-59e456fd53a6
		summarizeBy: sum
		sourceColumn: OrderTotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition orders = m
		mode: import
		queryGroup: 01_Stage
		source =
				let
				    Quelle = Table.Combine({ORDERS_2025, ORDERS_2026}),
				    #"Entfernte Spalten" = Table.RemoveColumns(Quelle,{"LegacyRef", "SourceFile", "GiftMessage", "OrderNotes"})
				in
				    #"Entfernte Spalten"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

