table ORDERS_2026
	lineageTag: a2a7dfdd-b28f-456d-8002-5c956ae16d27

	column OrderID
		dataType: string
		lineageTag: 5ab8421c-208f-4d6a-aab8-dc782e1635ef
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 4e3eb387-5b72-491b-a3de-d63ba79a6970
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column CustomerCity
		dataType: string
		lineageTag: dd23b120-a291-4e39-8f82-8dbfa2720a1a
		summarizeBy: none
		sourceColumn: CustomerCity

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		lineageTag: 5305b196-c2ac-4f7d-bf5e-62fd8e359b7a
		summarizeBy: none
		sourceColumn: RegionName

		annotation SummarizationSetBy = Automatic

	column ShipToCity
		dataType: string
		lineageTag: b8aa21c6-eb84-4c43-98a4-bc941fee06b4
		summarizeBy: none
		sourceColumn: ShipToCity

		annotation SummarizationSetBy = Automatic

	column BillToCity
		dataType: string
		lineageTag: 11290d7c-cfef-4491-8e6a-6c4b4af8764b
		summarizeBy: none
		sourceColumn: BillToCity

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 1b48c1a1-4af2-4097-b22b-195f693f4f4d
		summarizeBy: none
		sourceColumn: OrderDate

		variation Variation
			isDefault
			relationship: 5a441859-f07a-4b76-b3c2-b4899d48dcdc
			defaultHierarchy: LocalDateTable_d44201e6-75c3-47f3-9460-44f6256ac986.Datumshierarchie

		annotation SummarizationSetBy = Automatic

	column OrderChannel
		dataType: int64
		formatString: 0
		lineageTag: 28bd1413-9ef4-4cf4-b0d9-baec697a0709
		summarizeBy: sum
		sourceColumn: OrderChannel

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 6a197dd0-4347-4ff0-a585-5a7f82838017
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 626c780b-323b-4a19-bd94-a7337af95a86
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column OrderTotal
		dataType: double
		lineageTag: d701b42c-251f-419d-81f2-3d25c476ee6e
		summarizeBy: sum
		sourceColumn: OrderTotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderNotes
		dataType: string
		lineageTag: 58022246-2333-4fbe-af8d-457b0821687f
		summarizeBy: none
		sourceColumn: OrderNotes

		annotation SummarizationSetBy = Automatic

	column GiftMessage
		dataType: string
		lineageTag: b388584b-507e-4d1a-9ea1-0a5abafdda75
		summarizeBy: none
		sourceColumn: GiftMessage

		annotation SummarizationSetBy = Automatic

	partition ORDERS_2026 = m
		mode: import
		queryGroup: 01_Stage
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\dev\dimensional-data-modeling-portfolio\local-data\dataset.xlsx"), null, true),
				    ORDERS_2026_Sheet = Quelle{[Item="ORDERS_2026",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(ORDERS_2026_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"OrderID", type text}, {"CustomerName", type text}, {"CustomerCity", type text}, {"RegionName", type text}, {"ShipToCity", type text}, {"BillToCity", type text}, {"OrderDate", type datetime}, {"OrderChannel", Int64.Type}, {"Status", type text}, {"Priority", type text}, {"OrderTotal", type number}, {"OrderNotes", type text}, {"GiftMessage", type any}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

