table payments
	lineageTag: 38f9adae-1ba0-4139-800c-2398c1c34055

	column PaymentID
		dataType: string
		lineageTag: 7fbedf81-c357-47df-ae47-a2f689bf70c7
		summarizeBy: none
		sourceColumn: PaymentID

		annotation SummarizationSetBy = Automatic

	column InvoiceID
		dataType: string
		lineageTag: 25e57ce2-781d-4538-8d36-6d48e320ae8e
		summarizeBy: none
		sourceColumn: InvoiceID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: c11b16a3-a039-450c-ba53-aa44e9079590
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column PayDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 075d25b5-f9d7-4811-b69b-828ae7431567
		summarizeBy: none
		sourceColumn: PayDate

		variation Variation
			isDefault
			relationship: 418f9cb0-fb6e-4294-b925-f3e61ccbca18
			defaultHierarchy: LocalDateTable_00f20046-f372-4b55-9c97-aadaa4395c46.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Amount
		dataType: double
		lineageTag: ed8e1171-1525-4079-acf9-3e1d3962ff27
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition payments = m
		mode: import
		queryGroup: 01_Stage
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\dev\dimensional-data-modeling-portfolio\local-data\dataset.xlsx"), null, true),
				    payments_Sheet = Quelle{[Item="payments",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(payments_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"PaymentID", type text}, {"InvoiceID", type text}, {"CustomerName", type text}, {"PayDate", type date}, {"Amount", type number}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

