table security
	lineageTag: d908208e-e825-4cf5-b81f-debaf45f9781

	column Column1
		dataType: string
		lineageTag: e9c56c0c-af3b-48d1-89fc-44d9a46b294a
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 9989acb5-84a8-48b8-bcda-16ee5ddba698
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition security = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\Users\admin\Desktop\powerbi-ultimate-course\project_nightmare_datamodel\dataset.xlsx"), null, true),
				    security_Sheet = Quelle{[Item="security",Kind="Sheet"]}[Data],
				    #"Geänderter Typ" = Table.TransformColumnTypes(security_Sheet,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

