table Sheet1
	lineageTag: b0aefd59-d283-422b-881c-c3b10e1dc8d4

	column ShipmentID
		dataType: string
		lineageTag: 6390bdd7-b5cd-4e4a-bf1a-98c5eb789eeb
		summarizeBy: none
		sourceColumn: ShipmentID

		annotation SummarizationSetBy = Automatic

	column OrderID
		dataType: string
		lineageTag: c62c35b9-e7fe-4fc8-88db-c9d3830b6dd6
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column ShipMode
		dataType: string
		lineageTag: 5fa863cf-306e-46b2-a664-87f630721a5d
		summarizeBy: none
		sourceColumn: ShipMode

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b6f1918b-343a-42d1-b3d9-2a98dc5a916a
		summarizeBy: none
		sourceColumn: ShipDate

		variation Variation
			isDefault
			relationship: 6b3319b6-727d-40ba-8494-f268eb9972c8
			defaultHierarchy: LocalDateTable_f3cf50c2-5612-4c58-8948-786a3a972b25.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DeliveryDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 48cafc14-a3ab-4a92-9df2-0a1de5ad4ba1
		summarizeBy: none
		sourceColumn: DeliveryDate

		variation Variation
			isDefault
			relationship: 5beebb89-8d6f-4d15-8045-c8a4729421e6
			defaultHierarchy: LocalDateTable_727f9616-a7be-4b5d-8d92-7b756462a861.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Sheet1 = m
		mode: import
		queryGroup: 01_Stage
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\dev\dimensional-data-modeling-portfolio\local-data\dataset.xlsx"), null, true),
				    Sheet1_Sheet = Quelle{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"ShipmentID", type text}, {"OrderID", type text}, {"ShipMode", type text}, {"ShipDate", type date}, {"DeliveryDate", type date}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

