table shipments
	lineageTag: d7402d65-f36d-464d-a72e-357df68c74f0

	column ShipmentID
		dataType: string
		lineageTag: ff6351a3-47a3-4800-9d17-8185bd830ebf
		summarizeBy: none
		sourceColumn: ShipmentID

		annotation SummarizationSetBy = Automatic

	column OrderID
		dataType: string
		lineageTag: 7624975e-123a-49ca-8792-718cd8e4a4e3
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column ShipMode
		dataType: string
		lineageTag: 42c45c3d-87d8-46c9-9f95-ecabda09ed8e
		summarizeBy: none
		sourceColumn: ShipMode

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3c4946c2-978b-44e6-a412-2030d3b6c3d7
		summarizeBy: none
		sourceColumn: ShipDate

		variation Variation
			isDefault
			relationship: 8998ce1e-89aa-4288-a3aa-68ba3fb72cb1
			defaultHierarchy: LocalDateTable_c9ab9a4d-049c-46c1-9ee1-e128221832df.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DeliveryDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 806d47f1-11b3-4f5d-bbb6-83e39b039a8c
		summarizeBy: none
		sourceColumn: DeliveryDate

		variation Variation
			isDefault
			relationship: 712a5b45-5312-4ce0-84b9-8da65101620d
			defaultHierarchy: LocalDateTable_ffd96e46-84cf-4be3-bb48-6898965d45f6.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition shipments = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(File.Contents("C:\dev\dimensional-data-modeling-portfolio\local-data\dataset.xlsx"), null, true),
				    shipments_Sheet = Quelle{[Item="shipments",Kind="Sheet"]}[Data],
				    #"Höher gestufte Header" = Table.PromoteHeaders(shipments_Sheet, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"ShipmentID", type text}, {"OrderID", type text}, {"ShipMode", type text}, {"ShipDate", type date}, {"DeliveryDate", type date}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

